# https://taskfile.dev

version: '3'

includes:
  build: ./taskfiles/build.yml

tasks:

  up:
    desc: Install and link the basic set of utilities (assumes nvim, go, etc is installed)
    cmds:
      - task: build:starship-prompt:install
      - task: build:direnv:install
      - task: build:go:link
      - task: build:nvim:link
      - task: build:git:link
      - task: build:lazygit:install
      - task: build:goimports:install
      - task: link 
    silent: true

  link:
    desc: Links the items in this directory to their corresponding $HOME locations
    cmds:
      - ./scripts/link_items.sh
    silent: true
