# https://taskfile.dev

version: '3'

includes:
  build: ./taskfiles/build.yml

tasks:

  all:
    desc: Install and link everything needed/wanted
    cmds:
      - task: build:starship-prompt:install
      - task: build:direnv:install
      - task: build:go:install
      - task: build:lazygit:install
      - task: build:goimports:install
      - task: build:nvim:install
      - task: build:python:install
      - task: build:rust:install
      - task: link
    silent: true

  basic:
    desc: Install and link the basic set of utilities (assumes nvim, go, etc is installed)
    cmds:
      - task: build:starship-prompt:install
      - task: build:direnv:install
      - task: link 
    silent: true

  link:
    desc: Links the items in this directory to their corresponding $HOME locations
    cmds:
      - task build:go:link
      - task build:nvim:link
      - ./scripts/link_items.sh
    silent: true
